// 0  if Chef wins or 1 if Rick wins
// the number of digits of the integer generated by the winner

#include<bits/stdc++.h>
using namespace std;
#define ll long long

// ll countDigit(ll n){ 
//     ll count = 0;
//     while(n > 0){
//         count++;
//         n -= 9;
//     }
//     return count;
// }

int main(){
    ll t;
    cin>>t;
    while(t--){
        ll c, r;
        cin>>c>>r;
        if(abs(c-r) < 9){
            cout<<"1 "<<ceil((double)r/9)<<endl;
        } else {
            if(c > r){
                cout<<"1 "<<ceil((double)r/9)<<endl;
            } else if(c < r){
                cout<<"0 "<<ceil((double)c/9)<<endl;
            }
        }
    }
    return 0;
}